name: Deploy Vector-tile GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 20

      - run: npm i pnpm -g

      - name: Install dependencies
        run: pnpm i

      - name: Build examples
        run: npm run build-example

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: example-build/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
